package combat

import (
	"math"

	"github.com/dofusarena/go-server/internal/gamedata"
)

// This file implements the CastTestLineOfSight piece of
// docs/08-java-parity-roadmap.md Phase L, using the real map data wired in
// Phase K (Fight.mapData). It is now a bit-exact port of the reference's
// LineOfSightUtils.check()/getCellsInputs() 3D DDA algorithm (confirmed
// via the decompiled client source), not an approximation: earlier
// versions of this file used a simple 2D Bresenham walk over just X/Y,
// checking a single "any solid surface blocks everything" bool per cell.
// The real algorithm instead independently walks each of the X, Y, and Z
// axes at every half-integer cell-boundary crossing, and for each crossing
// checks the SPECIFIC per-edge/top/bottom line-of-sight flag the map data
// carries for that surface and that exact approach direction (see
// gamedata.LineOfSightValidAt/LineOfSightEndValidAt and ResolvedSurface's
// LineOfSight1/3/5/7/Top/Bottom fields) -- e.g. a wall can legitimately
// block sight from the north while still letting it pass from the east.
// This matters in practice: altitude (Z) differences between caster and
// target were entirely ignored by the old approximation, and a solid
// obstacle's blocking was all-or-nothing regardless of approach angle.

// hasLineOfSight reports whether nothing blocks a line between from and
// to, mirroring LineOfSightUtils.check(): the destination cell itself
// must pass the "end validity" check, and every intermediate cell-
// boundary crossing generated by the 3-axis DDA walk must pass its
// direction-specific validity check. Falls back to true (permissive) if
// no real map data is attached to this fight, matching the pattern used
// throughout Phase K's wiring (IsWalkable/ArrivalAltitude) of "never
// block a fight just because optional real map data isn't available."
func (f *Fight) hasLineOfSight(from, to Point3) bool {
	if f.mapData == nil {
		return true
	}
	if !f.mapData.LineOfSightEndValidAt(to.X, to.Y, to.Z) {
		return false
	}
	for _, in := range generateLOSCellInputs(from, to) {
		if !f.mapData.LineOfSightValidAt(in.pos.X, in.pos.Y, in.pos.Z, in.dir) {
			return false
		}
	}
	return true
}

// losCellInput is one 3D-DDA cell-boundary crossing: the cell being
// entered and which of its six line-of-sight flags to check for the
// direction of travel that crossed into it. Mirrors
// LineOfSightUtils.CellInput.
type losCellInput struct {
	pos Point3
	dir gamedata.LOSDirection
}

// generateLOSCellInputs mirrors LineOfSightUtils.getCellsInputs(from, to)
// field-for-field: an independent DDA walk over each of the X, Y, and Z
// axes, emitting one losCellInput at every half-integer cell-boundary
// crossing along that axis, tagged with the LOS direction that boundary
// represents (X-axis crossings -> SouthEast/NorthWest, Y-axis ->
// SouthWest/NorthEast, Z-axis -> Top/Bottom, matching combat/fighter.go's
// Direction8 grid vectors and gamedata.LOSDirection's doc comment). An
// axis with zero delta (from and to share that coordinate) contributes no
// crossings at all -- the reference's own loop condition degenerates to
// zero iterations in that case.
//
// This is a genuine port, not a reinterpretation: the reference source
// decompiled with lost `break` statements in its direction-selection
// switch (a JD-Core artifact -- every case appeared to fall through to
// every other), but Direction8's real enum ordinals (SOUTH_EAST=1,
// SOUTH_WEST=3, NORTH_WEST=5, NORTH_EAST=7, TOP=8, BOTTOM=9) confirm each
// axis/sign combination maps to exactly ONE direction, as implemented
// below.
func generateLOSCellInputs(from, to Point3) []losCellInput {
	origin := [3]float64{float64(from.X), float64(from.Y), float64(from.Z)}
	dest := [3]float64{float64(to.X), float64(to.Y), float64(to.Z)}
	var deltas [3]float64
	for c := 0; c < 3; c++ {
		deltas[c] = dest[c] - origin[c]
	}

	var out []losCellInput
	for coord := 0; coord < 3; coord++ {
		delta := deltas[coord]
		axeIncrement := -1.0
		increment := -0.5
		if delta > 0 {
			axeIncrement = 1.0
			increment = 0.5
		}
		firstAxe := origin[coord] + increment
		lastAxe := dest[coord] + increment

		for axe := firstAxe; axe != lastAxe; axe += axeIncrement {
			t := (axe - origin[coord]) / delta

			var dir gamedata.LOSDirection
			switch coord {
			case 0:
				if delta > 0 {
					dir = gamedata.LOSDirSouthEast
				} else {
					dir = gamedata.LOSDirNorthWest
				}
			case 1:
				if delta > 0 {
					dir = gamedata.LOSDirSouthWest
				} else {
					dir = gamedata.LOSDirNorthEast
				}
			default: // 2 (Z)
				if delta > 0 {
					dir = gamedata.LOSDirTop
				} else {
					dir = gamedata.LOSDirBottom
				}
			}

			var resolved [3]float64
			for c := 0; c < 3; c++ {
				val := (dest[c]-origin[c])*t + origin[c]
				switch {
				case c == coord:
					// The axis being crossed always resolves to the exact
					// boundary being stepped onto.
					if delta > 0 {
						resolved[c] = math.Ceil(val)
					} else {
						resolved[c] = math.Floor(val)
					}
				case isJavaHalfInteger(val):
					// Tie-break at an exact half-cell on a NON-crossed axis:
					// round toward the direction that axis is heading.
					if deltas[c] > 0 {
						resolved[c] = math.Ceil(val)
					} else {
						resolved[c] = math.Floor(val)
					}
				default:
					resolved[c] = javaRound(val)
				}
			}

			out = append(out, losCellInput{
				pos: Point3{X: int32(resolved[0]), Y: int32(resolved[1]), Z: int16(resolved[2])},
				dir: dir,
			})
		}
	}
	return out
}

// isJavaHalfInteger mirrors the reference's `val - (int)val == 0.5D` tie-
// break test exactly, including Java's (int) truncate-TOWARD-ZERO cast
// semantics (which Go's int32(float64) conversion also truncates toward
// zero, matching it -- unlike math.Floor, which would give the wrong
// answer for negative values).
func isJavaHalfInteger(val float64) bool {
	return val-float64(int32(val)) == 0.5
}

// javaRound mirrors java.lang.Math.round(double): round-half-UP (floor(v
// + 0.5)), NOT Go's math.Round (which rounds half away from zero and so
// disagrees with Java for negative half-integers, e.g. round(-0.5):
// Java=0, Go's math.Round=-1).
func javaRound(v float64) float64 {
	return math.Floor(v + 0.5)
}
