/*
 * Decompiled with CFR 0.152.
 */
/*
 * Renamed from oh
 */
public abstract class oh_2 {
    public static final String QM = "messageBoxDialog";
    public static final String QN = "popupDialog";
    public static final String QO = "interactiveBubbleDialog";
    public static final String QP = "progressDialog";
    public static final String QQ = "consoleDialog";
    public static final String QR = "optionsDialog";
    public static final String QS = "logonDialog";
    public static final String QT = "menuDialog";
    public static final String QU = "fightMenuDialog";
    public static final String QV = "reportBugDialog";
    public static final String QW = "guildDialog";
    public static final String QX = "guildCreationDialog";
    public static final String QY = "guildCoachStatsDialog";
    public static final String QZ = "notEnoughMembersDialog";
    public static final String Ra = "menuBarDialog";
    public static final String Rb = "menuBarEvolutionDialog";
    public static final String Rc = "menuBarTutoDialog";
    public static final String Rd = "menuBarTuto2Dialog";
    public static final String Re = "fightMenuBarDialog";
    public static final String Rf = "chatDialog";
    public static final String Rg = "privateMessageDialog";
    public static final String Rh = "coachCreationDialog";
    public static final String Ri = "coachStatisticsDialog";
    public static final String Rj = "ladderInformationDialog";
    public static final String Rk = "ladderInformationEvolutionDialog";
    public static final String Rl = "demonLadderInformationDialog";
    public static final String Rm = "fighterCreationDialog";
    public static final String Rn = "fighterCreationTutorialDialog";
    public static final String Ro = "randomFightCreationDialog";
    public static final String Rp = "randomFightSearchStatusDialog";
    public static final String Rq = "randomFightTeamManagementDialog";
    public static final String Rr = "timelineDialog";
    public static final String Rs = "fightEventCardsDialog";
    public static final String Rt = "fightPresentationDialog";
    public static final String Ru = "fightObservationDialog";
    public static final String Rv = "fightPlacementDialog";
    public static final String Rw = "fightResultDialog";
    public static final String Rx = "fightResultEvolutionDialog";
    public static final String Ry = "fightResultEvolutionTutoDialog";
    public static final String Rz = "fightResultEvolutionTimeChallengeDialog";
    public static final String RA = "fightResultEvolutionChallengeDialog";
    public static final String RB = "fightResultSubstitutesDetailsDialog";
    public static final String RC = "coachLevelUpDialog";
    public static final String RD = "fighterControlsDialog";
    public static final String RE = "fighterInformationsDialog";
    public static final String RF = "cardBookDialog";
    public static final String RG = "cardBookTutorialDialog";
    public static final String RH = "zaapDialog";
    public static final String RI = "singleCardDialog";
    public static final String RJ = "exchangeDialog";
    public static final String RK = "replayDialog";
    public static final String RL = "replayIdentificationCertificate";
    public static final String RM = "tournamentInformationDialog";
    public static final String RN = "totemTournamentDialog";
    public static final String RO = "tournamentTreeDialog";
    public static final String RP = "teamNameDialog";
    public static final String RQ = "newTeamTournamentDialog";
    public static final String RR = "team2vs2NameDialog";
    public static final String RS = "emissaryTutoDialog";
    public static final String RT = "mapDialog";
    public static final String RU = "graphicalDiagnosticsDialog";
    public static final String RV = "cardMasterDialog";
    public static final String RW = "demonIIDialog";
    public static final String RX = "splitCardMasterTradeDialog";
    public static final String RY = "splitDemonAffiliationTradeDialog";
    public static final String RZ = "newTeamManagementDialog";
    public static final String Sa = "teamManagementDialog";
    public static final String Sb = "teamManagementFighterListDialog";
    public static final String Sc = "teamManagementSelectedFighterDialog";
    public static final String Sd = "mailboxDialog";
    public static final String Se = "newMailDialog";
    public static final String Sf = "socialDialog";
    public static final String Sg = "chatFilterDialog";
    public static final String Sh = "sphereDetailsDialog";
    public static final String Si = "coachQuickEquipmentDialog";
    public static final String Sj = "tooltipDialog";
    public static final String Sk = "tooltipTutoDialog";
    public static final String Sl = "challengeDialog";
    public static final String Sm = "tournamentsSearchStatusDialog";
    public static final String Sn = "guildManagementDialog";
    public static final String So = "calendarDialog";
    public static final String Sp = "infosDialog";
    public static final String Sq = "tournamentTeamManagementDialog";
    public static final String Sr = "tournamentEvolutionDialog";
    public static final String Ss = "tournamentGraveyardDialog";
    public static final String St = "achievementDialog";
    public static final String Su = "fighterEquipmentDialog";
    public static final String Sv = "classicDialog";
    public static final String Sw = "evolutionDialog";
    public static final String Sx = "evolutionTeamManagementTutoDialog";
    public static final String Sy = "evolutionTeamManagementTuto2Dialog";
    public static final String Sz = "tournamentDetailsDialog";
    public static final String SA = "calendarTournamentDetailsDialog";
    public static final String SB = "evolutionSearchStatusDialog";
    public static final String SC = "classicSearchStatusDialog";
    public static final String SD = "fighterEvolutionEquipmentDialog";
    public static final String SE = "graveyardDialog";
    public static final String SF = "demonAffiliationDialog";
    public static final String SG = "cardPurchaseConfirmationDialog";
    public static final String SH = "fireworkDialog";
    public static final String SI = "customFightDialog";
    public static final String SJ = "customFightProfileLoadingDialog";
    public static final String SK = "customFightProfileSavingDialog";
    public static final String SL = "teamLoadDialog";
    public static final String SM = "customFightProfileDetailsDialog";
    public static final String SN = "fusionLabDialog";
    public static final String SO = "tournamentCreationDialog";
    public static final String SP = "tournamentAdminCreationDialog";
    public static final String SQ = "npcTalkDialog";
    public static final String SR = "unlockedColorsDialog";
    public static final String SS = "videoLoadingDialog";
    public static final String ST = "sphereBoardDialog";
    public static final short SU = 10000;
    public static final short SV = 20000;
    public static final short SW = 30000;
    public static final short SX = 30001;
    public static final short SY = 19500;
    public static final short SZ = 30000;
    public static final short Ta = 19501;
    public static final short Tb = 10000;
    public static final short Tc = 19500;
    public static final short Td = 10000;
    public static final short Te = 10000;
    public static final short Tf = 10001;
    public static final short Tg = 10000;
    public static final short Th = 10000;
    public static final short Ti = 10000;
    public static final short Tj = 19501;
    public static final short Tk = 10000;
    public static final short Tl = 10000;
    public static final short Tm = 10000;
    public static final short Tn = 10000;
    public static final short To = 19000;
    public static final short Tp = 10003;
    public static final short Tq = 12000;
    public static final short Tr = 12000;
    public static final short Ts = 10001;
    public static final short Tt = 10001;
    public static final short Tu = 10000;
    public static final short Tv = 10000;
    public static final short Tw = 10100;
    public static final short Tx = 10000;
    public static final short Ty = 10000;
    public static final short Tz = 10001;
    public static final short TA = 10010;
    public static final short TB = 10010;
    public static final short TC = 10100;
    public static final short TD = 10000;
    public static final short TE = 10001;
    public static final short TF = 10001;
    public static final short TG = 10001;
    public static final short TH = 10100;
    public static final short TI = 10001;
    public static final short TJ = 9000;
    public static final short TK = 13000;
    public static final short TL = 10000;
    public static final short TM = 20000;
    public static final short TN = 20000;
    public static final short TO = 30000;
    public static final short TP = 10000;
    public static final short TQ = 10000;
    public static final short TR = 10000;
    public static final short TS = 10000;
    public static final short TT = 10001;
    public static final short TU = 10000;
    public static final short TV = 10000;
    public static final short TW = 10001;
    public static final short TX = 10000;
    public static final short TY = 20000;
    public static final short TZ = 10000;
    public static final short Ua = 10000;
    public static final short Ub = 10000;
    public static final short Uc = 10000;
    public static final short Ud = 10000;
    public static final short Ue = 10000;
    public static final short Uf = 10000;
    public static final short Ug = 10000;
    public static final short Uh = 10000;
    public static final short Ui = 10000;
    public static final short Uj = 10000;
    public static final short Uk = 10000;
    public static final short Ul = 10000;
    public static final short Um = 10000;
    public static final short Un = 10000;
    public static final short Uo = 10000;
    public static final String Up = "chatDialog";

    public static String bq(String string) {
        return oh_2.br(string);
    }

    static String br(String string) {
        String string2 = String.format(mu_1.rM().rO(), string);
        if (!an_2.o(string2)) {
            return null;
        }
        return string2;
    }
}

