/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

public class sr
implements aGm {
    private Stack ajc = new Stack();
    private afq_1 ajd;

    public air_1 a(afq_1 afq_12, aji_1 aji_12) {
        this.ajd = afq_12;
        this.ajc.push(aji_12);
        aji_1 aji_13 = (aji_1)this.ajc.peek();
        aab_2 aab_22 = new aab_2();
        aab_22.b();
        aab_22.setElementMap(aji_13);
        aab_22.setMinSize(new agj_1(200, 150));
        aab_22.setNonBlocking(true);
        aab_22.setStyle("replay");
        aab_22.Ak();
        auW auW2 = new auW();
        auW2.b();
        auW2.setElementMap(aji_13);
        auW2.setAlign(ajn_1.dSC);
        aab_22.j(auW2);
        auW2.Ak();
        auW2.Aj();
        ei_1 ei_12 = ei_1.checkOut();
        aab_22.j(ei_12);
        ei_12.Ak();
        aht_1 aht_12 = aht_1.checkOut();
        aht_12.setElementMap(aji_13);
        aht_12.setExpandable(false);
        aht_12.setPrefSize(new agj_1(40, 0));
        ei_12.j(aht_12);
        aht_12.Ak();
        azc_0 azc_02 = new azc_0();
        azc_02.b();
        azc_02.setElementMap(aji_13);
        gb_0 gb_02 = new gb_0();
        gb_02.fS("popup(replayIdentificationCertificatePopup)");
        azc_02.setOnMouseEnter(gb_02);
        Se se = new Se();
        se.fS("closePopup(replayIdentificationCertificatePopup)");
        azc_02.setOnMouseExit(se);
        azc_02.setScaled(true);
        aht_12.j(azc_02);
        azc_02.Ak();
        afz_1 afz_12 = afz_1.checkOut();
        afz_12.setElementMap(aji_13);
        afz_12.setAttribute("style");
        afz_12.setName("replayIdentificationCertificateIcon");
        azc_02.j(afz_12);
        afz_12.Ak();
        av_1 av_12 = new av_1();
        av_12.b();
        av_12.setElementMap(aji_13);
        av_12.setElseValue("identificationCertificateInvalid");
        av_12.setValue("identificationCertificateValid");
        afz_12.j(av_12);
        av_12.Ak();
        du_0 du_02 = new du_0();
        du_02.b();
        du_02.setElementMap(aji_13);
        av_12.j(du_02);
        du_02.Ak();
        du_02.Aj();
        av_12.Aj();
        afz_12.Aj();
        String string = "replayIdentificationCertificatePopup";
        ai_2 ai_22 = new ai_2();
        ai_22.b();
        ai_22.setElementMap(aji_13);
        if (aji_13 != null && string != null) {
            aji_13.a(string, ai_22);
        }
        ai_22.setAlign(BT.aJU);
        ai_22.setHotSpotPosition(BT.aKa);
        azc_02.j(ai_22);
        ai_22.Ak();
        aht_1 aht_13 = aht_1.checkOut();
        aht_13.setElementMap(aji_13);
        aht_13.setExpandable(true);
        aht_13.setPrefSize(new agj_1(100, 0));
        ai_22.j(aht_13);
        aht_13.Ak();
        et_1 et_12 = new et_1();
        et_12.b();
        aht_13.j(et_12);
        et_12.Ak();
        OE oE = new OE();
        oE.b();
        oE.setElementMap(aji_13);
        oE.setStyle("identificationCertificate");
        et_12.j(oE);
        oE.Ak();
        pj_2 pj_22 = pj_2.checkOut();
        pj_22.setElementMap(aji_13);
        pj_22.setData(ahq_1.dNX);
        oE.j(pj_22);
        pj_22.Ak();
        pj_22.Aj();
        afz_1 afz_13 = afz_1.checkOut();
        afz_13.setElementMap(aji_13);
        afz_13.setAttribute("text");
        afz_13.setName("replayIdentificationCertificateText");
        oE.j(afz_13);
        afz_13.Ak();
        av_1 av_13 = new av_1();
        av_13.b();
        av_13.setElementMap(aji_13);
        String string2 = "%identificationCertificate.invalid%";
        string2 = string2.replace("%identificationCertificate.invalid%", add_1.aOG().kE("identificationCertificate.invalid"));
        av_13.setElseValue(string2);
        String string3 = "%identificationCertificate.valid%";
        string3 = string3.replace("%identificationCertificate.valid%", add_1.aOG().kE("identificationCertificate.valid"));
        av_13.setValue(string3);
        afz_13.j(av_13);
        av_13.Ak();
        du_0 du_03 = new du_0();
        du_03.b();
        du_03.setElementMap(aji_13);
        av_13.j(du_03);
        du_03.Ak();
        du_03.Aj();
        av_13.Aj();
        afz_13.Aj();
        oE.Aj();
        et_12.Aj();
        aht_13.Aj();
        ai_22.Aj();
        azc_02.Aj();
        awc_0 awc_02 = awc_0.checkOut();
        awc_02.setElementMap(aji_13);
        awc_02.setInsets(new Insets(10, 0, 10, 0));
        aht_12.j(awc_02);
        awc_02.Ak();
        awc_02.Aj();
        aht_12.Aj();
        ei_12.Aj();
        aab_22.Aj();
        return aab_22;
    }
}

